//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splendid.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Splendid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black	3	3	3	5	3	0
        ///Black	4	0	0	3	6	3
        ///Black	4	0	0	0	7	0
        ///Black	5	0	0	0	7	3
        ///Blue	3	3	0	3	3	5
        ///Blue	4	6	3	0	0	3
        ///Blue	4	7	0	0	0	0
        ///Blue	5	7	3	0	0	0
        ///Green	3	5	3	0	3	3
        ///Green	4	3	6	3	0	0
        ///Green	4	0	7	0	0	0
        ///Green	5	0	7	3	0	0
        ///Red	3	3	5	3	0	3
        ///Red	4	0	3	6	3	0
        ///Red	4	0	0	7	0	0
        ///Red	5	0	0	7	3	0
        ///White	3	0	3	3	5	3
        ///White	4	3	0	0	3	6
        ///White	4	0	0	0	0	7
        ///White	5	3	0	0	0	7.
        /// </summary>
        internal static string BlueTier {
            get {
                return ResourceManager.GetString("BlueTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black	0	2	1	0	0	0
        ///Black	0	1	1	0	1	2
        ///Black	0	1	0	1	2	1
        ///Black	0	0	0	0	3	0
        ///Black	0	3	0	0	0	0
        ///Black	0	4	0	0	0	0
        ///Black	0	0	0	4	0	0
        ///Black	1	0	0	0	0	4
        ///Blue	0	1	1	1	1	0
        ///Blue	0	0	0	0	2	1
        ///Blue	0	0	2	1	0	0
        ///Blue	0	0	2	0	0	2
        ///Blue	0	1	0	0	1	3
        ///Blue	0	0	0	0	4	0
        ///Blue	0	0	4	0	0	0
        ///Blue	1	1	0	0	0	2
        ///Green	0	0	0	2	0	2
        ///Green	0	0	2	0	2	0
        ///Green	0	0	1	2	1	1
        ///Green	0	1	0	2	2	0
        ///Green	0	0	0	0	0	3
        ///Green	0	0	1	3	1	0
        ///Green	0	1	3	1	0	0
        ///Green	1	1	1	0	1	1
        ///Red	0	0	1	1	1	1
        ///Red	0	1	0	1	1	1
        ///Red	0	0	0	2	1	0
        ///Red	0	2	0	2	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GreenTier {
            get {
                return ResourceManager.GetString("GreenTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	3	3	3	0
        ///4	4	0	0	0
        ///3	3	0	0	3
        ///0	0	0	4	4
        ///3	0	0	3	3
        ///0	0	3	3	3
        ///3	3	3	0	0
        ///0	4	4	0	0
        ///4	0	0	0	4
        ///0	0	4	4	0.
        /// </summary>
        internal static string Nobles {
            get {
                return ResourceManager.GetString("Nobles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black	1	3	2	2	0	0
        ///Black	1	3	0	3	0	2
        ///Black	2	0	1	4	2	0
        ///Black	2	5	0	0	0	0
        ///Black	2	0	0	5	3	0
        ///Black	3	0	0	0	0	6
        ///Blue	1	0	2	2	3	0
        ///Blue	1	0	2	3	0	3
        ///Blue	2	2	0	0	1	4
        ///Blue	2	0	5	0	0	0
        ///Blue	2	5	3	0	0	0
        ///Blue	3	0	6	0	0	0
        ///Green	1	2	3	0	0	2
        ///Green	1	3	0	2	3	0
        ///Green	2	4	2	0	0	1
        ///Green	2	0	0	5	0	0
        ///Green	2	0	5	3	0	0
        ///Green	3	0	0	6	0	0
        ///Red	1	2	0	0	2	3
        ///Red	1	0	3	0	2	3
        ///Red	2	1	4	2	0	0
        ///Red	2	0	0	0	0	5
        ///Red	2	3	0	0	0	5
        ///Red	3	0	0	0	6	0
        ///White	1	0	0	3	2	2
        ///White	1	2	3	0	3	0
        ///White	2	0	0	1	4	2
        ///White	2	0	0	0	5	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YellowTier {
            get {
                return ResourceManager.GetString("YellowTier", resourceCulture);
            }
        }
    }
}
